### PR TITLE
Adds pre-commit checks to the repo --SGPROJ-1544

### PR DESCRIPTION
**Pull request by DJKaswa**
## Change description

> I added all pre-commit checks for this repo. Once reviewed and approved, you can merge it to main. At that point, the repo will be ready to be imported to tf-auto once approved on that side.

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1]() 

### Development

- [x] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to task tracker where applicable

### CODE REVIEW

**Review by JoseMotto-sg — DISMISSED** [review]
Please submit a new release version when merging to main

**Comment by DJKaswa** [comment]
> Please submit a new release version when merging to main

will do, thanks!

**Comment by DJKaswa** [comment]
@JoseMotto-sg you'll have to review again in order for me to merge this. It's staled because you required a change and the version can only be done after merging.

**Review by JoseMotto-sg — APPROVED** [review]
LGTM

**Pull request merged**
